### PR TITLE
Fix infinite loop with ie11

### LINKED ISSUE #4: Using session reducer together with local reducer causes ie11 to freeze up
Below are the minimal code setup to reproduce the issue:

```
import React from 'react'
import ReactDOM from 'react-dom'
import { useSessionStorageReducer, useLocalStorageReducer } from 'react-storage-hooks'

function Root() {
  const [state1, dispatch1] = useSessionStorageReducer('session', () => {}, {})
  const [state2, dispatch2] = useLocalStorageReducer('local', () => {}, {})
  return (
    <div>hi</div>
  )
}

ReactDOM.render(<Root />, document.getElementById('root'))
```

### PR DESCRIPTION
**Pull request by michaelbirchler**
Fixes #4

### CODE REVIEW

**Comment by soyguijarro** [comment]
Hey @michaelbirchler, first of all thanks a lot for your contribution!

- I'm not sure I quite understand what's going on here, could you explain how this solves the issue?
- Also the code seems a little strange to me, I mean the comparison between two values and then with `false`. Wouldn't `event.newValue !== event.oldValue` be enough?
- I don't have a Windows installation handy at the moment, but I saw you mentioned the original reporter in the issue so let's see what they have to say.

**Comment by michaelbirchler** [comment]
>I'm not sure I quite understand what's going on here, could you explain how this solves the issue? I mean, I'm guessing the event handler is being called constantly with the same value but I don't see how that would happen. Could this be related to #5 and be solved once that's fixed as well?

I'm using the `useSessionStorageReducer` hook on my app, while it worked on every tested browser expect on IE 11. On IE 11 I've experienced an endless loop. Adding the condition prevented the error to happen again. With IE 11 the event listener `window.addEventListener('storage', handleStorageChange);` compared to others browsers the event is triggered on every page load with IE11. Yes, this this pull request could also resolve #5. 

>The code seems a little strange to me. I mean the comparison between two values and then with false. Wouldn't event.newValue !== event.oldValue be enough?

@soyguijarro yes, of course you could do it with `event.newValue !== event.oldValue`, it's just a matter of taste :-). I've changed the condition with c96d3426d7d5ec0cdbeaa90ca509d5d4e672eb70.

**Comment by michaelbirchler** [comment]
I've noticed that this pull request does not resolve IE11 crashing if multiple dispatch events in combination with `useSessionStorageReducer` are processed successively.

**Comment by soyguijarro** [comment]
I'm working on a full rewrite of the library, so this PR is no longer relevant. I'll take the issue into account in the new version though, thanks for taking the time to contribute!

**Comment by PupoSDC** [comment]
Did the full rewrite lead anywhere? Im hitting this issue on `4.0.1`.

**Pull request closed without merging**
